### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by hurbeana** [hurbeana/FilmArchivePlanner#1]
## Description
Add an option to export singular movies to a pretty printed pdf.

## Tasks
- [ ] Research libraries/tools to create a nicely formatted pdf
- [ ] Discuss with TW/TR how it should look like, what should be included and where/how
- [ ] Implement functionality for export in backend
- [ ] Implement button to trigger said export
