### ISSUE TITLE
CSV Export in Human Readable Format

### ISSUE THREAD

**Issue by hurbeana** [hurbeana/FilmArchivePlanner#2]
## Description
Just like the export functionality, TW/TR requires a CSV export functionality where no references are contained, but the data itself.

The request also comes with changing it to be able to import singular CSVs into the importer (needs discussion if this makes sense or should be split off into another *new* feature)

## Tasks
- [ ] Discuss with TW/TR what exactly should be exported and how it should look like when exported
- [ ] Implement functionality in backend
- [ ] Implement functionality in frontend (also ask how it should work in terms of where it should be found in the frontend)
