### ISSUE TITLE
Movies Length Formatting

### ISSUE THREAD

**Issue by hurbeana** [hurbeana/FilmArchivePlanner#3]
## Description
Movies length should not be given in minutes only. Either minutes + seconds or "HH:MM:SS" format.

## Tasks
- [x] Discuss with TW/TR how this should be concretely implemented
- [x] Implement in backend
- [x] Implement in frontend (careful for breaking changes with other components of frontend)
  - [x] Rename the field from "Duration in Minutes" to "Duration" in frontend

**Comment by hurbeana** [comment]
fixed
