### ISSUE TITLE
Rename Field "Submission Cat."

### ISSUE THREAD

**Issue by hurbeana** [hurbeana/FilmArchivePlanner#4]
## Description
The field "Submission Cat." inside movies should be renamed to just "Category". Ideally this should be done across front and backend to keep naming consistent.

## Tasks
- [x] Implement request in frontend
- [ ] Implement request in backend
- [ ] Test for breaking changes

**Comment by hurbeana** [comment]
Should be fixed in the frontend for now only in 4-rename-field-submission-cat
