### ISSUE TITLE
Change field "Trailer File" to Link

### ISSUE THREAD

**Issue by hurbeana** [hurbeana/FilmArchivePlanner#5]
## Description
The field in movies "Trailer File" should now be a Link to an external resource that gets opened when clicked (should be clickable). Careful to also adjust the Filemanagement aspect here, since were dealing with files.

Field should also be renamed to "Preview Link".

## Tasks
- [x] Remove any trace of "Trailer File" in backend
- [x] Remove any trace of "Trailer File" in frontend
- [x] Add string field "Preview Link" in backend
- [x] Make the field visible in all Movie Views and have it by a hyperlink that opens in a new window

**Comment by hurbeana** [comment]
fixed in branch, rebased onto master
