### ISSUE TITLE
Add new "Reference Nr" Field

### ISSUE THREAD

**Issue by hurbeana** [hurbeana/FilmArchivePlanner#6]
## Description
A new field for movies (I think only for movies, needs inquiry) is needed:
- Name: Reference Nr
- Dtype: Plain String
- Required: No

## Tasks
- [x] Add the field in the backend, new movies should be creatable with the field
- [x] Add the field in all of the movie views
- [x] Check for breaking changes

**Comment by hurbeana** [comment]
fixed in branch 6, also searchable #7 is done too
