### ISSUE TITLE
New Field "Reference Nr" should be searchable

### ISSUE THREAD

**Issue by hurbeana** [hurbeana/FilmArchivePlanner#7]
## Description
The new field (see issue #6) should be searchable. It is only required in the *Advanced Search*, but if possible it would also be nice to have in the full text search.

## Tasks
- [x] Make the field searchable in backend
- [x] Add a new field in the advanced search
- [x] Test for functionality

**Comment by hurbeana** [comment]
done with #6 in one commit
